config/routes.rb
Rails.application.routes.draw do
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    User.create(user_params)
  end

  def index
    @user = User.all
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    user = User.find(params[:id])
    user.update(user_params)
  end

  private

  def user_params
    params.require(:user).permit(:name, :age)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ResourcesCrudSample</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/create.html.erb
<h1>登録完了</h1>
<%= link_to "一覧画面へ", users_path %>

app/views/users/destroy.html.erb
<h1>削除完了</h1>
<%= link_to "一覧画面へ", users_path %>

app/views/users/edit.html.erb
<%= form_for @user, url: user_path(@user), html: { method: :patch } do |f| %>
<p>更新</p>
<p>お名前:<%= f.text_field :name %></p>
<p>年齢:<%= f.text_field :age %></p>
<input type="submit" value"送信">
<% end %>

app/views/users/index.html.erb
<%= link_to "投稿画面へ", new_user_path %>
<% @user.each do |user| %>
  <p>
    <%= user.name %>
    <%= user.age %>
    <%= link_to "削除", user_path(user), method: :delete, data: {confirm: "削除しますか？"} %>
    <%= link_to "編集", edit_user_path(user) %>
  </p>
<% end %>

app/views/users/new.html.erb
<%= form_for @user, url: users_path, html: { method: :post } do |f| %>
  <p>新規登録</p>
  <p>お名前:<%= f.text_field :name %></p>
  <p>年齢:<%= f.text_field :age %></p>
  <input type="submit" value="送信">
<% end %>

app/views/users/update.html.erb
<h1>更新完了</h1>
<%= link_to "一覧画面へ", users_path%>